### ISSUE TITLE
Curly brace parsing in Component

### ISSUE THREAD

**Issue by JeffML** [bigpipe/react-jsx#20]
(originally posted at https://github.com/apollographql/apollo-client/issues/4312)

**Intended outcome:**

On a Mutation component, it seems that the block must begin on a new line after the start tag:
```
const Submit = props => <Mutation mutation={DELETE}>
  {mDelete => (
    <Mutation mutation={UPSERT}>
      {mUpsert => (
        <input type="submit" value="Submit Changes" style={{ float: 'right' }}
          onClick={evt => submitAction({
            evt, returnTo: props.setPage, mDelete, mUpsert, refetch: props.refetch,
          })} />
      )}
    </Mutation>
  )}
</Mutation>;
```

**Actual outcome:**

if the curly brace is placed immediately after the start tag, then a runtime error occurs:
    `<Mutation mutation={UPSERT}> {mUpsert => (...`

Error:

> index.js:1446 Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `Mutation`, expected `function`.
    in Mutation (at SubmitCancel.js:82)

**Versions**

  System:
    OS: macOS High Sierra 10.13.6
  Binaries:
    Node: 10.12.0 - /usr/local/bin/node
    npm: 6.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Safari: 12.0.2
  npmPackages:
    apollo-boost: ^0.1.22 => 0.1.22
    react-apollo: ^2.3.2 => 2.3.2
```

**Comment by 3rd-Eden** [comment]
The apollo-client doesn't use `react-jsx`, they are referring to JSX as the language spec, not specifically to this module.

**Comment by JeffML** [comment]
Okay, that's fine.  I took a peek at the ECMA spec,  but wasn't able to find anything about [PrimaryExpression](https://www.ecma-international.org/ecma-262/8.0/index.html#sec-primary-expression) having to start on a new line after the start tag of the containing element. But it is a large spec, so I probably missed it.
